### Read data from income.csv and scale the relevant features using standardization

In [ ]:
import pandas as pd

In [5]:
df = pd.read_csv("income.csv")
df.head()

      Name  Age  Income  Buy
0      Rob   27   70000  Yes
1  Michael   29   90000   No
2    Mohan   29   61000  Yes
3   Ismail   28   60000  Yes
4     Kory   42  150000   No

In [9]:
features = df[['Age','Income']]
features

    Age  Income
0    27   70000
1    29   90000
2    29   61000
3    28   60000
4    42  150000
5    39  155000
6    41  160000
7    38  162000
8    36  156000
9    35  130000
10   37  137000
11   26   45000
12   27   48000
13   28   51000
14   29   49500
15   32   53000
16   40   65000
17   41   63000
18   43   64000
19   39   80000
20   41   82000
21   39   58000

In [11]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaled_data = scaler.fit_transform(features)
scaled_data

array([[-1.35605536, -0.48068427],
       [-1.00915747, -0.01015907],
       [-1.00915747, -0.69242061],
       [-1.18260641, -0.71594687],
       [ 1.24567876,  1.40141653],
       [ 0.72533193,  1.51904783],
       [ 1.07222982,  1.63667914],
       [ 0.55188299,  1.68373166],
       [ 0.20498511,  1.54257409],
       [ 0.03153617,  0.93089133],
       [ 0.37843405,  1.09557515],
       [-1.5295043 , -1.06884077],
       [-1.35605536, -0.99826199],
       [-1.18260641, -0.92768321],
       [-1.00915747, -0.9629726 ],
       [-0.48881065, -0.88063069],
       [ 0.89878087, -0.59831557],
       [ 1.07222982, -0.64536809],
       [ 1.4191277 , -0.62184183],
       [ 0.72533193, -0.24542167],
       [ 1.07222982, -0.19836915],
       [ 0.72533193, -0.76299939]])